= Client Side Ost Wallet Browser Sdk
:doctype: book

== Introduction

OST Wallet SDK Browser is a web application development SDK that enables developers to integrate the functionality of a non-custodial crypto-wallet into consumer applications.
The sdk creates user's Api and session keys.
Altough the device keys are created, they are not stored in the browser.
Users must use your mobile application to authorize the session keys and perform transactions.

= Table of Contents

* <<client-side-ost-wallet-browser-sdk,Client Side Ost Wallet Browser Sdk>>
 ** <<introduction,Introduction>>
* <<table-of-contents,Table of Contents>>
* <<quick-start-guide,Quick start guide>>
 ** <<installation,Installation>>
 ** <<import-ostwalletsdk,Import OstWalletSdk>>
 ** <<initialize-the-sdk-and-setup-user-s-device,Initialize the Sdk and setup user's device.>>
* <<detailed-documentation-reference,documentation,Detailed Documentation Reference>>
 ** xref:./sdk_initialization.adoc[Setup & Initialization]
 ** xref:./workflows.adoc[Workflows]
 ** xref:./ost_json_api.adoc[OstJsonApi]
 ** xref:./useful_methods.adoc[Useful Methods]
 ** xref:./development_environment_setup.adoc[Setup Development Environemnt]

= Quick start guide

== Installation

Install the npm module

----
npm install @ostdotcom/ost-wallet-sdk-browser --save
----

More more information please refer xref:./sdk_initialization.adoc[Setup And Initialization] guide.

== Import OstWalletSdk

----
import OstWalletSdk from '@ostdotcom/ost-wallet-sdk-browser'
----

== Initialize the Sdk and setup user's device.

Use the below code to initialize the sdk and setup user's device.
The below code defines `initializeAndSetupOstSdk` method that you could use once your applications' page has loaded or before user's first wallet interaction by calling the `initializeAndSetupOstSdk` method.
The `initializeAndSetupOstSdk` return a `Promise` that only resolves when both(initialize and setup) the tasks are completed without any errors.

NOTE: +++<u>+++Your code needs to *invoke or call*+++</u>+++ the `initializeAndSetupOstSdk` method.

[source,js]
----
const sdkConfig = {
     token_id: "1129"
     api_endpoint: "https://api.stagingost.com/testnet/v2/"
     sdk_endpoint: "https://sdk-mappy.stagingpepocoin.com/v1/index.html"
     create_session_qr_timeout: 300
     max_workflow_count: 50
   }
----

____
*Note*

* _create_session_qr_timeout_: Sdk polls for session till `create_session_qr_timeout` seconds.
It doesn't expires QR code.
* _max_workflow_count_: It keeps `max_workflow_count` number of non pending workflows and removes remaining workflows.
____

[source,js]
----
  /*
      Define a method initializeAndSetupOstSdk to combine init sdk method and setupdevice workflow.
   */

  /**
   * initializeAndSetupOstSdk - initializes the sdk and then performs setup device workflow for the logged-in user.
   * @param  {String} ost_user_id Ost User Id of the logged-in user.
   * @param  {String} token_id    Token-Id of the your brand token economy.
   * @return {Promise}            a Promise that only resolves when both the tasks are completed without any failuers.
   */
  const initializeAndSetupOstSdk = (ost_user_id, token_id) => {
    const registerDevice(apiParams) {
      /**
       * Write your code here to send the api params to your server.
       * Use the server side sdk to register the device.
       */

    }

    const setupDeviceWorkflow = () => {
      let sdkDelegate =  new OstSetupDeviceDelegate();
      // Define register device.
      sdkDelegate.registerDevice = function( apiParams ) {
        console.log(LOG_TAG, "registerDevice");
        return registerDevice(apiParams);
      };

      //Define flowComplete
      sdkDelegate.flowComplete = (ostWorkflowContext , ostContextEntity ) => {
        console.log("setupDeviceWorkflow :: sdkDelegate.flowComplete called");

        _resolve( ostContextEntity );
      };

      //Define flowInterrupt
      sdkDelegate.flowInterrupt = (ostWorkflowContext , ostError) => {
        console.log("setupDeviceWorkflow :: sdkDelegate.flowInterrupt called");
        _reject( ostError );
      };

      // Return a promise that invokes the workflow.
      return new Promise( (res, rej) => {
        _resolve = res;
        _reject  = rej;

        // Invoke the workflow.
        OstWalletSdk.setupDevice(ost_user_id, token_id, sdkDelegate);
      });
    };

  return OstWalletSdk.init( sdkConfig )
        .then(() => {
          return oThis.setupDeviceWorkflow();
        })
  }
----

= Detailed Documentation Reference

* xref:./sdk_initialization.adoc[Setup and Initialization]
* xref:./workflows.adoc[Workflows]
* xref:./OstJsonApi.adoc[OstJsonApi]
* xref:./useful_methods.adoc[Other Methods]
* xref:./development_environment_setup.adoc[Setup Development Environemnt]
